### ISSUE TITLE
getting None from active() 

### ISSUE THREAD

**Issue by irom77** [PaloAltoNetworks/pandevice#14]
I'm trying to use 'active()' to find active firewall in my HA cluster. My cluster members have IPs '10.34.2.21' and '10.34.2.20'. Currently '10.34.2.21' is active
```
$ cat pandevice.fw.commit_all.py
#!/usr/bin/python
from pandevice import base
from pandevice import firewall
from pandevice import panorama
from pandevice import policies
from pandevice import objects
from pandevice import network
from pandevice import device
fw = base.PanDevice('10.34.2.21', 'admin', 'password',vsys='vsys1')
print fw.active()
```

But no matter what cluster member I test, I got 'None' in response ?

```
$ python pandevice.fw.commit_all.py
None
```

**Comment by btorresgil** [comment]
Hello.

I did some testing and found that the active() method is working correctly, in that it is correctly returning the active firewall object.  However, the string representation of that object is the string: "None", which is why it is printing None when you run the script.  Note that this only happens because you're using a `PanDevice` object instead of a `Firewall` object.  For example:

    # Using Firewall object
    >>> fw = firewall.Firewall("10.0.0.1", "admin", "password")
    >>> fw.active()
    <Firewall '10.5.172.32' 'vsys1' at 0x11164bc10>

    # Using PanDevice object
    >>> fw2 = base.PanDevice("10.5.172.32", "admin", "password")
    >>> fw2.active()
    <PanDevice None at 0x111678f10>

I made a change to the source so it prints the hostname of the active firewall instead of 'None'.  This will go out in the next release.  But this issue should not affect any operations, it is purely cosmetic.

Note that when there is only one firewall object, the active() method will always return that firewall object.  If you're trying to determine which firewall is active in a running HA pair, you need to add both firewalls as objects to an ha pair, and refresh the active state from the live devices.  For example:

    # Check which firewall is active
    >>> fw1 = firewall.Firewall("10.0.0.1", "admin", "password")
    >>> fw2 = firewall.Firewall("10.0.0.2", "admin", "password")
    >>> fw1.set_ha_peers(fw2)
    >>> fw1.refresh_ha_active()
    'active'
    
    # fw1 is active, so `fw2.active()` returns the fw1 object
    >>> fw2.active()
    <Firewall '10.0.0.1' 'vsys1' at 0x11164bc10>

Using HA with pandevice isn't well documented right now.  We'll use this open issue to track the cosmetic change to the code mentioned above and the documentation enhancement.

Thanks for the feedback.

**Comment by irom77** [comment]
Yeah, works now. Thnx again

```
[docker@nms02m ~]$ cat pandevice.fw.commit_all.py 
#!/usr/bin/python
from pandevice import base
from pandevice import firewall
from pandevice import panorama
from pandevice import policies
from pandevice import objects
from pandevice import network
from pandevice import device
import time

fw1 = firewall.Firewall('10.34.2.20', 'admin', '')
fw2 = firewall.Firewall('10.34.2.21', 'admin', '')
#Establish an HA peer relationship between two PanDevice objects
fw1.set_ha_peers(fw2)
#Refresh which device is active using the live device
print fw1.refresh_ha_active()
print fw2.refresh_ha_active()
```

so fw2 is active based on below

```
[docker@nms02m ~]$ python pandevice.fw.commit_all.py 
passive
active
```
