### ISSUE TITLE
escape character 

### ISSUE THREAD

**Issue by irom77** [PaloAltoNetworks/pandevice#16]
I have function like below
```
def commit(job, fw):       
        print "fw" + str(job) + " is ACTIVE"
        fw.commit()
        time.sleep(120)
        cmd = "show jobs processed \| match mit"
        print fw.op(cmd, xml=True)
        return
```
but getting following error. Do you know how to correctly escape that '|' ?
```
$ python pandevice.fw.commit_all.py
active
fw2 is ACTIVE
Traceback (most recent call last):
  File "pandevice.fw.commit_all.py", line 26, in <module>
    commit(2,fw2)
  File "pandevice.fw.commit_all.py", line 16, in commit
    print fw.op(cmd, xml=True)
  File "/usr/lib/python2.7/site-packages/pandevice/firewall.py", line 201, in op
    return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)
  File "/usr/lib/python2.7/site-packages/pandevice/base.py", line 1664, in op
    element = self.xapi.op(cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer)
  File "/usr/lib/python2.7/site-packages/pandevice/base.py", line 1573, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError: Illegal parameter [request]
```

**Comment by lampwins** [comment]
My suspicion is that this is expected behavior and that `|` is not valid when issuing cli commands via api. When you think about it, you are asking the api to do two things here. Other vendors that expose the cli via api do not support this kind of thing. It is best practice to do this "matching" in the client that is consuming the api.

**Comment by shinmog** [comment]
The API does not have a hook to run the `match` filtering because that is only valid on the CLI.  But depending on what your goal is, there are a few ways to get around this.

1) The Firewall's `commit()` does return a job ID that you can capture, and thus do followup queries on.  Specifically:

```
job_id = fw.commit()
time.sleep(120)
cmd = 'show jobs id "{0}"'.format(job_id)
print fw.op(cmd, xml=True)
```
 -or-

2) The function `commit()` does have an optional param you can pass in, `sync=True`, that will block until the commit is finished.  The sleep I see in your code snippet above seems to imply that you are looking for this behavior.  When specifying `sync=True`, a dict is returned that gives a bit more detailed information as to the job's results.  So you could replace everything after your first print with this:

```
print fw.commit(sync=True)
```

Let us know if this works for you.

**Comment by irom77** [comment]
It says now that id 'None' is not a valid integer` ?
`pandevice.errors.PanDeviceXapiError:  show -> jobs -> id 'None' is not a valid integer`
