### ISSUE TITLE
'name' parameter is missing from AddressGroup documentation

### ISSUE THREAD

**Issue by writememe** [PaloAltoNetworks/pandevice#167]
Hi Team,

When trying to create an address group using the class pandevice.objects.AddressGroup, the class does not have the `name` parameter:

Documentation:
https://pandevice.readthedocs.io/en/latest/module-objects.html#pandevice.objects.AddressGroup
Code:
https://pandevice.readthedocs.io/en/latest/_modules/pandevice/objects.html#AddressGroup

This means that I cannot create address groups using Pandevice, however I can assign address objects to address groups which are already created.

Is this intentional or is it something which is an oversight?

Thanks,
Daniel

**Comment by btorresgil** [comment]
Hi Daniel,

Thanks for bringing this to our attention.  There is actually a `name` parameter.  The problem is in the documentation which we will need to fix by adding `name`.

If you try to use the `name` parameter of an `AddressGroup` instance, it should work fine even through it doesn't reflect in the documentation.

Here's an example:

```
>>> from pandevice import objects
>>> addr_obj = objects.AddressObject('my-object', '10.0.1.1')
>>> addr_grp = objects.AddressGroup('my-group', [addr_obj])
>>> addr_grp.about()
{'static_value': [<AddressObject my-object 0x10daed550>],
 'dynamic_value': None,
 'description': None,
 'tag': None,
 'name': 'my-group'
}
```

Notice that the name exists on the AddressGroup in the call to `.about()`.

Thanks!
 -Brian

**Comment by writememe** [comment]
Hi Brian,

Thanks heaps for getting back to me, really appreciate it!
