### ISSUE TITLE
Connecting to Active device in HA pair

### ISSUE THREAD

**Issue by deverm12** [PaloAltoNetworks/pandevice#210]
Hi ,

I am trying to use refresh_ha_active() functionality so that script always run on active device.  As per my understanding once i set the peer it will check internally and run it on active box or my understanding is wrong here ? I am trying to run test route cmd to pull interface details and then later run test security cmd and in order that we need to always connect to active box to pull details . I am trying below . Could you please suggest on below  : 

 

NOTE:  If i am giving device1 IP active device member and device2 IP standby IP , this works fine . However if i am giving device1 IP as standby and device2 IP as active , then its failing as from standby its not pulling interface details.

 

deviceip1 = input('Enter device FQDN/IP: ')
deviceip2 = input('Enter device2 FQDN/IP: ')
user = input('Enter username: ')

fw = Firewall(deviceip1, user, getpass())
fw.set_ha_peers(Firewall(deviceip2,user,getpass()))

fw.refresh_ha_active()

srcip = input ('Enter SOURCE IP: ')
dstip = input ('Enter DEST IP: ')
dstport = input ('Enter dstport: ')
proto = input('Enter protocol number: ')

output1 = fw.xapi.op(cmd='<test><routing><fib-lookup><virtual-router>default</virtual-router><ip>{}</ip></fib-lookup></routing></test>'.format(srcip) , cmd_xml=False)

**Comment by btorresgil** [comment]
You're definitely doing this correctly expect for one caveat, the `op()` method always goes to the firewall you call it on, not necessarily the active firewall. This is because there are many situations where you'd want to get operational status of the passive firewall.

The only change you need to make is to refer to which firewall is active before calling the `op()` method.

> Also, a side note, I recommend the firewall's `fw.op()` method, not the `fw.xapi.op()` method. The difference is `fw.op()` can return an Element or XML string, assumes `cmd_xml=True` by default, and is HA aware so can retry the command on the peer device.

So, instead of:
```python
output1 = fw.xapi.op(cmd='default{}'.format(srcip) , cmd_xml=False)
```

Do this:
```python
output1 = fw.active().op(cmd='default{}'.format(srcip), cmd_xml=False, retry_on_peer=True)
```

Now the command will always go to the active firewall. `retry_on_peer=True` means that in the event that the active firewall is down, pandevice will automatically switch its internal state to treat the other firewall as active and run the command again on the other firewall.

In general, here are techniques for directing your API call to a particular firewall in an HA pair, assuming the following setup:

```python
fw1 = Firewall('10.0.0.1', user, pass)
fw2 = Firewall('10.0.0.2', user, pass)
fw1.set_ha_peers(fw2)
fw1.refresh_ha_active()
```

| Method call | Firewall used |
| --- | --- |
| fw1 | fw1 |
| fw2 | fw2 |
| fw1.[ha_peer](https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.PanDevice.ha_peer) | fw2 |
| fw2.[ha_peer](https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.PanDevice.ha_peer) | fw1 |
| fw1.[active()](https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.PanDevice.active) | Whichever is active |
| fw1.[passive()](https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.PanDevice.passive) | Whichever is passive |
| fw1.[ha_pair()](https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.PanDevice.ha_pair) | List with both fw1 and fw2 |
| fw1.[map_ha()](https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.PanDevice.map_ha) | Call function on both fw1 and fw2 |

**Comment by deverm12** [comment]
Thanks for your help , i will try this and update the thread.

**Comment by deverm12** [comment]
It's working , again thanks for your help .
