### ISSUE TITLE
Unable to use element() or element_str() methods with Firewall pandevice object

### ISSUE THREAD

**Issue by chrisgoodwins** [PaloAltoNetworks/pandevice#227]
## Describe the bug
When using a Firewall pandevice object, I'm unable to use the element or element_str methods. 
## Expected behavior

The methods should return a ElementTree object or an XML string
## Current behavior
It 2 errors depending on when it's called, see example below

## Steps to reproduce

```
>>> fw_device = Firewall('10.10.10.10', 'username', 'password')
>>> fw_device.element()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pandevice\firewall.py", line 226, in element
    raise ValueError("Serial number must be set to generate element")
ValueError: Serial number must be set to generate element
>>> 
>>> fw_device.add(ServiceObject()).refreshall(fw_device)
[<ServiceObject SMTP-25 0x2bb69159430>, <ServiceObject SMTP-587 0x2bb68ad01c0>, <ServiceObject tcp-8080 0x2bb6914a3d0>]
>>> 
>>> fw_device.element()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pandevice\firewall.py", line 228, in element
    if self.parent == self.panorama() and self.serial is not None:
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pandevice\base.py", line 1030, in panorama
    raise err.PanDeviceNotSet("No Panorama set for object tree")
pandevice.errors.PanDeviceNotSet: No Panorama set for object tree
```

## Workaround
```
>>> fw_device = PanDevice('10.10.10.10', 'username', 'password')
>>> fw_device.element()
<Element '' at 0x000002BB68F69040>
```

## Your Environment

- Version used:
- python 3.8.1
- Windows 10
- Latest version of pandevice and pan-python

**Comment by btorresgil** [comment]
Hello,

This is by design. There's a couple reasons for this:

1. If you call `.element()` on a Firewall, it will expect you are trying to get the XML for a firewall in Panorama, not the children elements of the firewall. For example, if you have a tree that looks like this:
`Panorama -> DeviceGroup -> Firewall -> ServiceObject`
Calling `.element()` on the ServiceObject gives the XML for that object on the Firewall. Calling `.element()` on the Firewall gives the XML for that Firewall in the DeviceGroup.

2. There are very few use cases where you want to operate on an entire firewall configuration. Typically you are doing a very specific configuration change on the firewall, such as adding a security rule and objects and profiles attached to it. So there's very few time you'd want an element from a Firewall object.

If you tell me what you're trying to do accomplish by calling `.element()` on a Firewall, I can try to help you with another way to do it.

**Comment by chrisgoodwins** [comment]
Ok, that makes sense then. Thanks for the clarification. I also just realized that if I need the entire xml config, then I can just...
`fw_device.op('show config running')`
