### ISSUE TITLE
fw.op(cmd, xml=True) the command cannot be longer than 4 sections

### ISSUE THREAD

**Issue by tianwei758** [PaloAltoNetworks/pandevice#229]
## Describe the bug

I have a script calling fw.op() to run a panos cli but I found it failed with exception error. Here is my  command call.

        element_response = fw.op('clear session all filter ant-rule test_nat-a', xml=True)

Got below errors:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandevice/base.py", line 3469, in method
    super_method(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pan/xapi.py", line 951, in op
    self.__type_op(cmd, vsys, extra_qs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pan/xapi.py", line 974, in __type_op
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  clear -> session -> all -> filter -> nat-rule is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prod_switch.py", line 62, in <module>
    element_response = fw.op('clear session all filter nat-rule test_nat-1', vsys=None, xml=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandevice/firewall.py", line 190, in op
    return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandevice/base.py", line 3606, in op
    element = self.xapi.op(cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandevice/base.py", line 3486, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError:  clear -> session -> all -> filter -> nat-rule is invalid

If I change the command to 'show system info' it will be fine. Or if I change the command to anything to equal or less than 4 sections the command will run successfully, like 'xxx xxx xxx xxx'.

## Expected behavior

Expecting the command to be executed without error.

## Current behavior

Currently I received error like above.

## Possible solution

it looks like a bug in xapi.py but not too sure.

## Steps to reproduce

1. create a firewall object
fw = firewall.Firewall(HOSTNAME, USERNAME, PASSWORD)
2. run an operation command
fw.op('clear session all filter nat-rule xxx') or fw.op('show counter global filter delta yes')

## Screenshots

<img width="934" alt="Screen Shot 2020-06-12 at 10 06 18 am" src="https://user-images.githubusercontent.com/12075719/84450725-67830b00-ac94-11ea-9045-fc80be3b7e99.png">

## Context

It failed my automation work flow.

## Your Environment

- Version used: PANOS 9.0.8
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python 3.7.7
- Operating System and version (desktop or mobile): MacOS laptop
- Link to your project: not on github

**Comment by bsucevic** [comment]
show system info gets translated to:

<show><system><info></info></system></show>

The name of the NAT rule in the clear session all command that you entered has a non-tagged value, it looks like this:  

<clear><session><all><filter><nat-rule>test_nat-a</nat-rule></filter></all></session></clear>

The .op() command that you used is probably generating this which is invalid:

<clear><session><all><filter><nat-rule><test_nat-a></test_nat-a></nat-rule></filter></all></session></clear>

I believe the issue is that the op() function is not handling values that are not contained within XML tags.  In order to resolve this issue the op() function would need to be aware of every command available on the firewall and where they use non-tagged values.

A workaround is to enter the command as XML like this so you can enter the non-tagged value:

rule = 'test_nat-a'
xml_command = '<clear><session><all><filter><nat-rule>' + rule + '</nat-rule></filter></all></session></clear>'

try:
    results = firewall_object.op(xml_command, cmd_xml=False)
catch:
    print('Exception occurred')

**Comment by btorresgil** [comment]
You must put non-keyword sections in double quotes. Like this:

```python
element_response = fw.op('clear session all filter nat-rule "test_nat-a"', xml=True)
```
