### ISSUE TITLE
HOW TO REMOVE POLICY

### ISSUE THREAD

**Issue by EdoardoMDP** [PaloAltoNetworks/pandevice#238]
Hi all,

I'm writing a script that removes policies that have hit counts equal to 0. How can I delethe them? what is the method to use. In the documentation I have not found the method to access the hit count variable, does it exist?

import pandevice
import pandevice.firewall
import pandevice.policies
import pandevice.objects
import pandevice.base
import pandevice.device
HOSTNAME = 'ip'
API_KEY = 'key'
fw = pandevice.firewall.Firewall(hostname=HOSTNAME, api_key=API_KEY)
rulebase = pandevice.policies.Rulebase()
fw.add(rulebase)
rules = pandevice.policies.SecurityRule.refreshall(rulebase)
for rule in rules:
	if(rule.hit_count == 0 )
		**fw.remove(rule)
		rule.apply()**

THANKS

**Comment by btorresgil** [comment]
Instead of:

```python
fw.remove(rule)
rule.apply()
```

Do this instead:

```python
rule.delete()
```

Explanation:

`remove()` only affects the config tree in python, not the live device, then you do an `apply()` on the rule, but that rule isn't attached to anything because it was removed, so pandevice doesn't know what to apply it to.

A `delete()` affects the live device, so pandevice looks at the name of the rule you're deleting and immediately deletes the rule with that name from the live device it's attached to in the config tree, removing it from the config tree at the same time.

Here's more information about the different methods you can call on each object:
https://pandevice.readthedocs.io/en/latest/useful-methods.html
