### ISSUE TITLE
Support for changes to firewall/Panorama administrators

### ISSUE THREAD

**Issue by ivanbojer** [PaloAltoNetworks/pandevice#38]

**Comment by shinmog** [comment]
Looking at the debug output when I change the password from the GUI, it's unclear to me that the way it's executing the password update is invocable from the API.  Typically you see some xpath, submit XML document, and response XML document.  Instead I see stuff referring to what looks like resources that can only be accessed internally.  I'll need to investigate if this is possible from the API or not.

**Comment by btorresgil** [comment]
Talked with Ivan and updated the title.  The request is to support device administrators, including changing the administrator's password.

Ivan found a way to change the password.  You can't do it with just config XML because it requires a phash (password hash) which we can't generate ourselves.  But we can request the firewall to generate this password hash with the op command:  `request password-hash username "myuser" password "mypass"`  This will generate a phash that you can pass into the XML for the administrator in the `phash` param.
