### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/pandevice#7]
This is an enhancement request to support python 3.

If you would like to vote for python 3 support, please comment below with:
- the exact versions of python 3 you require
- the reason you use python 3 instead of 2.7
- if there is a project on hold due to no python 3 support

Thank you for your help.  You may also contact me with details at btorres-gil@paloaltonetworks.com.

**Comment by FliesLikeABrick** [comment]
Hi @btorresgil   - we have a growing codebase that is almost entirely python3, yours is one of the only 2 modules we use that does not support python3.

We use python3 due to the strong recommendation in the python ecosystem that 2.7 not be used for new codebases, and our codebase is entirely written in the last 12 months or less.  We also utilize a variety of (albeit small) python3 features.

We do have a few new security tools being developed this year that will rely heavily on pandevice functionality, and we will not implement these tools with 2.7 due to the need to reuse organization-centric code of ours that is in the python3 codebase.  These tools are likely on hold until pandevice has python3 support or we find a reasonable alternative package.

We would love support for 3.5.3.  I wish I could say that we could contribute towards the effort of python3 support, but we lack the resources and professional software development experience on our team of network engineers.

**Comment by btorresgil** [comment]
@FliesLikeABrick 

Python 3 support has been added to the develop branch and will be released as version 0.5.0 very soon.  Thank you for your comments above, they really helped us prioritize this feature.  Please let us know your experience with pandevice in python 3.

Thanks!

**Comment by FliesLikeABrick** [comment]
@btorresgil  thank you very much - I was extending our use of the PAN API this last week and noticed that python3 happened to be working!  So far the experience is positive, no issues but I will actively engage or submit patches if we come across any.  Thanks again!
